#include <commands/Init.hpp>

#include <iostream>
#include <fstream>
#include <string>
#include <filesystem>
#include <memory>

std::string Init::getName() const { return "init"; }

std::string_view Init::getHelp() const {
    return INIT_HELP;
}

static inline void initProject(const std::string& project_name) {
    if (std::filesystem::exists(project_name)) {
        std::cout << "error: folder already exists: " << project_name << std::endl;
        return;
    }
    std::filesystem::create_directory(project_name);
    std::filesystem::create_directory(project_name + "/api");
    std::filesystem::create_directory(project_name + "/static");

    std::ofstream outfile(project_name + "/tiramisu.yaml");
    if (!outfile.is_open()) {
        std::cerr << "Error: Could not create tiramisu.yaml\n";
        return;
    }

    outfile << "# Tiramisu Project Configuration\n"
            << "project:\n"
            << "  name: \"" << project_name << "\""
            << "  domain: \"localhost\" # generated by default. Override with \n\n"
            << "environments:\n"
            << "  # Use 'tiramisu host add' to append target server nodes here\n"
            << "  # local:\n"
            << R"(    # host: "127.0.0.1")" << '\n' 
            << R"(    # user: "root")" << '\n'
            << R"(    # identity: ~/.ssh/id_rsa)" << '\n'
            << "    #  port: " << 22 << std::endl;
    outfile.close();

    std::cout << "project " + project_name + " succesfully created\n";
}

void Init::execute(const Command& command) {
    if (command.arguments.size() < 1) throw std::runtime_error(std::string(getHelp()));
    
    auto const project_name = command.arguments.front();
    std::string default_api_path = "api/v1";
    // std::cout << "Init\n";
    // auto const sub_command = command.arguments[1];

    // if (sub_command == "-h" || sub_command == "--help") {
    //     getHelp();
    //     return;
    // } else if (sub_command == "--prefix") {
    //     try {
    //         default_api_path = command.arguments.at(2);
    //     } catch (const std::out_of_range& e) {
    //         std::cout << "error: " << e.what() << std::endl;
    //     }
    // }

    initProject(project_name);
}
